"""add ppt config table

Revision ID: add_ppt_config_table
Revises: ccbe9bd211b3
Create Date: 2025-01-27 10:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

import open_webui.internal.db

# revision identifiers, used by Alembic.
revision: str = "add_ppt_config_table"
down_revision: Union[str, None] = "ccbe9bd211b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ppt_config",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), default=False, nullable=False),
        sa.Column(
            "api_url", sa.String(), default="https://open.docmee.cn", nullable=False
        ),
        sa.Column("api_key", sa.String(), default="", nullable=False),
        sa.Column("credits_per_ppt", sa.Integer(), default=10, nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ppt_config")
    # ### end Alembic commands ###
