name: Frontend Build

on:
  push:
    branches:
      - main
      - dev
      - release
    paths-ignore:
      - 'backend/**'
      - 'pyproject.toml'
      - 'uv.lock'
  pull_request:
    branches:
      - main
      - dev
      - release
    paths-ignore:
      - 'backend/**'
      - 'pyproject.toml'
      - 'uv.lock'

jobs:
  build:
    name: 'Format & Build Frontend'
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Check System Memory
        run: |
          echo "=== System Memory Info ==="
          free -h
          echo "=== Node.js Memory Limit ==="
          node -e "console.log('Max heap size:', v8.getHeapStatistics().heap_size_limit / 1024 / 1024 / 1024, 'GB')"

      - name: Format Frontend
        run: npm run format

      - name: Run i18next
        env:
          NODE_OPTIONS: --max-old-space-size=8192
        run: npm run i18n:parse

      - name: Check for Changes After Format
        run: git diff --exit-code

      - name: Build Frontend
        env:
          NODE_OPTIONS: --max-old-space-size=16384
        run: npm run build

  test-frontend:
    name: 'Frontend Unit Tests'
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=8192
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run vitest
        env:
          NODE_OPTIONS: --max-old-space-size=12288
        run: npm run test:frontend
